In [161]:
import pandas as pd
import numpy as np
np.set_printoptions(suppress=True)
data = pd.read_csv(r"C:\Users\pavan\Downloads\SP500.csv")

In [47]:
data.head()

Date   Open   High    Low  Close  Adj Close   Volume
0  1950-01-03  16.66  16.66  16.66  16.66      16.66  1260000
1  1950-01-04  16.85  16.85  16.85  16.85      16.85  1890000
2  1950-01-05  16.93  16.93  16.93  16.93      16.93  2550000
3  1950-01-06  16.98  16.98  16.98  16.98      16.98  2010000
4  1950-01-09  17.08  17.08  17.08  17.08      17.08  2520000

In [49]:
data['Date'] = pd.to_datetime(data['Date'])

#### Dataframe to array Conversion

In [107]:
array_dat = data.to_numpy()

In [108]:
array_dat[:5]

array([[Timestamp('1950-01-03 00:00:00'), 16.66, 16.66, 16.66, 16.66,
        16.66, 1260000],
       [Timestamp('1950-01-04 00:00:00'), 16.85, 16.85, 16.85, 16.85,
        16.85, 1890000],
       [Timestamp('1950-01-05 00:00:00'), 16.93, 16.93, 16.93, 16.93,
        16.93, 2550000],
       [Timestamp('1950-01-06 00:00:00'), 16.98, 16.98, 16.98, 16.98,
        16.98, 2010000],
       [Timestamp('1950-01-09 00:00:00'), 17.08, 17.08, 17.08, 17.08,
        17.08, 2520000]], dtype=object)

#### Q1. The highest daily gain and its date, the highest daily loss and its date,

In [35]:
## Daily Gain
array_dat[array_dat[:,2]==max(array_dat[:,2])][0,[0,2]]

array(['2018-01-26', 2872.8701170000004], dtype=object)

In [36]:
## Daily Loss
array_dat[array_dat[:,3]==max(array_dat[:,3])][0,[0,3]]

array(['2018-01-29', 2851.47998], dtype=object)

#### Q2. The most daily transaction volume and its date,

In [34]:
array_dat[array_dat[:,-1]==max(array_dat[:,-1])][0,[0,-1]]

array(['2008-10-10', 11456230000], dtype=object)

In [29]:
array_dat[array_dat[:,2]==max(array_dat[:,2])]

array([['2018-01-26', 2847.47998, 2872.8701170000004, 2846.179932,
        2872.8701170000004, 2872.8701170000004, 3443230000]], dtype=object)

#### Q4. a yearly report which has annual average open price, close price, transaction volume and gain/loss from 1950 to 2018, and the most profitable year,

In [109]:
## year and month derivation from date.
array_dat = np.insert(array_dat,1,[array_dat[i,0].year for i in range(array_dat.shape[0])],1)
array_dat = np.insert(array_dat,1,[array_dat[i,0].month for i in range(array_dat.shape[0])],1)

In [141]:
array_dat[0]

array([Timestamp('1950-01-03 00:00:00'), 1, 1950, 16.66, 16.66, 16.66,
       16.66, 16.66, 1260000], dtype=object)

In [156]:
year_l,open_price,close_price,vol =[],[],[],[]
for year in np.unique(array_dat[:,2]):
    year_l.append(year)#year
    open_price.append(array_dat[(array_dat[:,2]==year)][:,3].mean())#Open
    close_price.append(array_dat[(array_dat[:,2]==year)][:,7].mean())#Close
    vol.append(array_dat[(array_dat[:,2]==year)][:,-1].mean())#Volume

In [157]:
yearly_result_array = np.array([year_l,open_price,close_price,vol])
yearly_result_array

array([[1.95000000e+03, 1.95100000e+03, 1.95200000e+03, 1.95300000e+03,
        1.95400000e+03, 1.95500000e+03, 1.95600000e+03, 1.95700000e+03,
        1.95800000e+03, 1.95900000e+03, 1.96000000e+03, 1.96100000e+03,
        1.96200000e+03, 1.96300000e+03, 1.96400000e+03, 1.96500000e+03,
        1.96600000e+03, 1.96700000e+03, 1.96800000e+03, 1.96900000e+03,
        1.97000000e+03, 1.97100000e+03, 1.97200000e+03, 1.97300000e+03,
        1.97400000e+03, 1.97500000e+03, 1.97600000e+03, 1.97700000e+03,
        1.97800000e+03, 1.97900000e+03, 1.98000000e+03, 1.98100000e+03,
        1.98200000e+03, 1.98300000e+03, 1.98400000e+03, 1.98500000e+03,
        1.98600000e+03, 1.98700000e+03, 1.98800000e+03, 1.98900000e+03,
        1.99000000e+03, 1.99100000e+03, 1.99200000e+03, 1.99300000e+03,
        1.99400000e+03, 1.99500000e+03, 1.99600000e+03, 1.99700000e+03,
        1.99800000e+03, 1.99900000e+03, 2.00000000e+03, 2.00100000e+03,
        2.00200000e+03, 2.00300000e+03, 2.00400000e+03, 2.005000

#### Q3. a monthly report for year 2017-2018, which has monthly average open price, close price, transaction volume and gain/loss, and a query to find all of the months which have certain range of open prices

In [142]:
array_dat

array([[Timestamp('1950-01-03 00:00:00'), 1, 1950, ..., 16.66, 16.66,
        1260000],
       [Timestamp('1950-01-04 00:00:00'), 1, 1950, ..., 16.85, 16.85,
        1890000],
       [Timestamp('1950-01-05 00:00:00'), 1, 1950, ..., 16.93, 16.93,
        2550000],
       ...,
       [Timestamp('2018-04-25 00:00:00'), 4, 2018, ..., 2639.399902,
        2639.399902, 3499440000],
       [Timestamp('2018-04-26 00:00:00'), 4, 2018, ..., 2666.939941,
        2666.939941, 3665720000],
       [Timestamp('2018-04-27 00:00:00'), 4, 2018, ..., 2669.909912,
        2669.909912, 3219030000]], dtype=object)

In [159]:
month_l,monthly_avg_open,monthly_avg_close,monthly_avg_vol =[],[],[],[]
for month in np.unique(array_dat[:,1]):
    month_l.append(month)#year
    monthly_avg_open.append(array_dat[(array_dat[:,1]==month)][:,3].mean())#Open
    monthly_avg_close.append(array_dat[(array_dat[:,1]==month)][:,7].mean())#Close
    monthly_avg_vol.append(array_dat[(array_dat[:,1]==month)][:,-1].mean())#Volume

In [160]:
monthly_result_array = np.array([month_l,monthly_avg_open,monthly_avg_close,monthly_avg_vol])
monthly_result_array.T

array([[1.00000000e+00, 5.38658878e+02, 5.38693080e+02, 9.22798311e+08],
       [2.00000000e+00, 5.55376968e+02, 5.55448098e+02, 9.26201994e+08],
       [3.00000000e+00, 5.58084964e+02, 5.58365713e+02, 9.38565674e+08],
       [4.00000000e+00, 5.61634638e+02, 5.61908749e+02, 9.22492905e+08],
       [5.00000000e+00, 5.37514951e+02, 5.37651368e+02, 8.79650812e+08],
       [6.00000000e+00, 5.40314628e+02, 5.40242669e+02, 8.73219395e+08],
       [7.00000000e+00, 5.41979748e+02, 5.42111879e+02, 8.61644389e+08],
       [8.00000000e+00, 5.41273562e+02, 5.41127184e+02, 8.24172630e+08],
       [9.00000000e+00, 5.38466075e+02, 5.38324701e+02, 9.06422107e+08],
       [1.00000000e+01, 5.38457953e+02, 5.38761766e+02, 9.36216388e+08],
       [1.10000000e+01, 5.56864032e+02, 5.57249066e+02, 9.07776811e+08],
       [1.20000000e+01, 5.56192928e+02, 5.56440462e+02, 8.38438477e+08]])

#### Q5. A every other five year report which has every five year average open price, close price, transaction volume and gain/loss from 1950 to 2018, and the most profitable five year,

In [164]:
np.set_printoptions(suppress=True)
yearly_result_array  = yearly_result_array.T

In [173]:
cnt=0
start=1950
while end<2018:
    end=start+5
    print(start,end)
    start=end
    cnt=cnt+1

1950 1955
1955 1960
1960 1965
1965 1970
1970 1975
1975 1980
1980 1985
1985 1990
1990 1995
1995 2000
2000 2005
2005 2010
2010 2015
2015 2020


In [184]:
yearly_result_array[(yearly_result_array[:,0]>=1950) & (yearly_result_array[:,0]<=1955),1]
yearly_result_array[(yearly_result_array[:,0]>=1950) & (yearly_result_array[:,0]<=1955),2]
yearly_result_array[(yearly_result_array[:,0]>=1950) & (yearly_result_array[:,0]<=1955),3]

array([[   1950.        ,      18.39726916,      18.39726916,
        2009236.94779116],
       [   1951.        ,      22.32188759,      22.32188759,
        1717590.36144578],
       [   1952.        ,      24.4961601 ,      24.4961601 ,
        1308160.        ],
       [   1953.        ,      24.7225897 ,      24.7225897 ,
        1413147.41035857],
       [   1954.        ,      29.72408735,      29.72408735,
        2269761.9047619 ],
       [   1955.        ,      40.49884918,      40.49884918,
        2573214.28571429]])

In [192]:
fy_year_l,fy_open_price,fy_close_price,fy_vol =[],[],[],[]
cnt=0
start=end=1950
while end<2018:
    end=start+5
    print(f"{start}-{end} avg computed and saved in array!")
    fy_year_l.append(f"{start}-{end}")
    fy_open_price.append(yearly_result_array[(yearly_result_array[:,0]>=start) & (yearly_result_array[:,0]<=end),1].mean())
    fy_close_price.append(yearly_result_array[(yearly_result_array[:,0]>=start) & (yearly_result_array[:,0]<=end),2].mean())
    fy_vol.append(yearly_result_array[(yearly_result_array[:,0]>=start) & (yearly_result_array[:,0]<=end),3].mean())
    start=end
    cnt=cnt+1

1950-1955 avg computed and saved in array!
1955-1960 avg computed and saved in array!
1960-1965 avg computed and saved in array!
1965-1970 avg computed and saved in array!
1970-1975 avg computed and saved in array!
1975-1980 avg computed and saved in array!
1980-1985 avg computed and saved in array!
1985-1990 avg computed and saved in array!
1990-1995 avg computed and saved in array!
1995-2000 avg computed and saved in array!
2000-2005 avg computed and saved in array!
2005-2010 avg computed and saved in array!
2010-2015 avg computed and saved in array!
2015-2020 avg computed and saved in array!


In [193]:
fiveYear_result_array = np.array([fy_year_l,fy_open_price,fy_close_price,fy_vol])
fiveYear_result_array.T

array([['1950-1955', '26.69347384666817', '26.69347384666817',
        '1881851.8183452839'],
       ['1955-1960', '48.50485536656382', '48.50485536656382',
        '2708414.786907122'],
       ['1960-1965', '70.62516759792071', '70.63705629109761',
        '4428444.619879226'],
       ['1965-1970', '90.76007339287521', '90.76644781844902',
        '9955481.745136002'],
       ['1970-1975', '94.50462734000882', '94.50075362144071',
        '15341843.276685223'],
       ['1975-1980', '100.65849391166842', '100.70358739002864',
        '27731966.40316206'],
       ['1980-1985', '145.63235553664228', '145.70310144023827',
        '73744424.83844657'],
       ['1985-1990', '272.18722677968077', '272.29671913162935',
        '153813554.4105653'],
       ['1990-1995', '429.8797452068139', '430.0526339340947',
        '240076086.59568906'],
       ['1995-2000', '987.0491365077551', '987.6159343484311',
        '633060807.950719'],
       ['2000-2005', '1153.2176759239844', '1153.073549165248'